services:
  - type: web
    name: doevida-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: node app.js
    envVars:
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
